'use client';
import './globals.css'
import "./lib/hexStyles.css"
import { Inter } from 'next/font/google'
import { TwitterProvider } from './context/TwitterContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tweeter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <TwitterProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </TwitterProvider>
  )
}
